# Generated by Django 3.1.2 on 2021-06-12 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colegio',
            fields=[
                ('id_colegio', models.CharField(blank=True, max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('provincia', models.CharField(max_length=255)),
                ('departamento', models.CharField(max_length=255)),
                ('distrito', models.CharField(max_length=255)),
                ('direccion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Herramienta',
            fields=[
                ('id', models.CharField(blank=True, max_length=8, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('cantidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_man', models.CharField(blank=True, max_length=8)),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_persona', models.CharField(blank=True, max_length=8, unique=True)),
                ('dni', models.CharField(max_length=9)),
                ('nombre', models.CharField(max_length=255)),
                ('apellidos', models.CharField(max_length=255)),
                ('celular', models.CharField(max_length=12)),
                ('sexo', models.CharField(blank=True, max_length=1, null=True)),
                ('f_nacimiento', models.DateField(blank=True, null=True)),
                ('correo', models.CharField(max_length=255)),
                ('activo', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Punto_acopio',
            fields=[
                ('id', models.CharField(blank=True, max_length=8, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('departamento', models.CharField(max_length=50)),
                ('provincia', models.CharField(max_length=50)),
                ('distrito', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Transportista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc', models.CharField(max_length=8)),
                ('nombre', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=50)),
                ('celular', models.CharField(max_length=15)),
                ('persona_contacto', models.CharField(max_length=50, null=True)),
                ('interprovincial', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.CharField(blank=True, max_length=8, primary_key=True, serialize=False)),
                ('costo', models.FloatField()),
                ('tipo_carga', models.CharField(max_length=100)),
                ('ruc_trans', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Voluntario_mantenimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_voluntario_mantenimiento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='database.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Voluntario_entrega',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_viaje', models.ManyToManyField(to='database.Viaje')),
                ('id_voluntario_entrega', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='database.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=50)),
                ('correo_baika', models.CharField(blank=True, max_length=255, null=True)),
                ('id_staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='database.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco', models.CharField(max_length=100)),
                ('cuenta_banco', models.CharField(max_length=20)),
                ('monto', models.FloatField()),
                ('id_socio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='database.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Responsable_acopio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_punto_acopio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='database.punto_acopio')),
                ('id_responsable_acopio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='database.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.CharField(blank=True, max_length=8, primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('id_colegio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.colegio')),
                ('id_viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.viaje')),
            ],
        ),
        migrations.CreateModel(
            name='Embajador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_embajador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='database.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Donante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_donante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_colegio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='database.colegio')),
                ('id_director', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='database.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Bicicleta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_bici', models.CharField(blank=True, max_length=8)),
                ('marca', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
                ('tamano_aro', models.IntegerField()),
                ('sexo', models.CharField(max_length=1)),
                ('color', models.CharField(max_length=20, null=True)),
                ('estado', models.CharField(max_length=50)),
                ('almacen', models.BooleanField()),
                ('id_donante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.donante')),
                ('id_entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.entrega')),
                ('id_punto_acopio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.punto_acopio')),
                ('id_viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.viaje')),
            ],
        ),
        migrations.CreateModel(
            name='Bici_arregla_herr_man',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parche', models.IntegerField(null=True)),
                ('aceite', models.BooleanField(null=True)),
                ('grasa', models.BooleanField(null=True)),
                ('pedal_cantidad', models.IntegerField(null=True)),
                ('cadena', models.IntegerField(null=True)),
                ('mango', models.IntegerField(null=True)),
                ('taco_freno', models.IntegerField(null=True)),
                ('id_bicicleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.bicicleta')),
                ('id_herramienta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.herramienta')),
                ('id_mantenimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.mantenimiento')),
            ],
        ),
        migrations.CreateModel(
            name='Beneficiario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estatura', models.FloatField()),
                ('tiempo_caminata', models.FloatField()),
                ('id_beneficiario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='database.persona')),
                ('id_colegio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.colegio')),
            ],
        ),
    ]
